---
  - name: Create hoarderapp ZFS volume
    community.general.zfs:
      name: "{{ HORDERAPP_STORAGE_ZFS_POOL }}/{{ HORDERAPP_STORAGE_ZFS_FS }}"
      state: present
      extra_zfs_properties:
        mountpoint: "{{ HORDERAPP_PATH }}"
